spring.profiles.active=local,dev
spring.application.name=printing.data.process.batch
groupId=${project.groupId}

spring.batch.jdbc.initialize-schema=always


management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.metrics.enabled=true
management.metrics.enable.all=true

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

#datasource.type.mssql=true
#mssql.url=jdbc:sqlserver://CM-MAIN\\SQLEXPRESS01:1433;databaseName=PrintingDB;encrypt=true;trustServerCertificate=true;
#mssql.username=sa
#mssql.password=admin

datasource.type.maria=true
#maria.url=... into application-local.properties
#maria.username=... into application-local.properties
#maria.password=...  into application-local.properties

#spring.data.mongodb.uri=mongodb+srv://masouras7:nvw08pKuYNPfJLID@cluster0.odazyaw.mongodb.net/trace?retryWrites=true&w=majority&appName=Cluster0

thread.pool.size=10